import ROOT
import os,sys
from ROOT import TGraphErrors
from array import array
from ROOT import *
#from TColor import TColor

#f=ROOT.TFile.Open("testNEW8_ext.root")
#f=ROOT.TFile.Open("newVerticesReReco.root")
#f_sim=ROOT.TFile.Open("../../VdmSimulatorFileTreeAnalyzedDG_bunch51_Sim.root")
f=ROOT.TFile.Open("/eos/cms/store/user/jsalfeld/vdmScan_2016ReRecoJan/mergedJan172016.root")
#f_sim=ROOT.TFile.Open("../VdmSimulatorFileTreeAnalyzedDG_bunch51_Sim.root")
#f_sim=ROOT.TFile.Open("../../VdmSimulatorFileTreeAnalyzedDG_Bunch1631_with_Offset.root")

ROOT.gStyle.SetOptStat(0)

vscan=array('d')
vscanerror=array('d')

vscan_sim=array('d')
vscanerror_sim=array('d')

RMSY1=array('d')
RMSerrorY1=array('d')
RMSX1=array('d')
RMSerrorX1=array('d')
MeanY1=array('d')
MeanerrorY1=array('d')
MeanX1=array('d')
MeanerrorX1=array('d')

RMSY2=array('d')
RMSerrorY2=array('d')
RMSX2=array('d')
RMSerrorX2=array('d')
MeanY2=array('d')
MeanerrorY2=array('d')
MeanX2=array('d')
MeanerrorX2=array('d')

RMSY3=array('d')
RMSerrorY3=array('d')
RMSX3=array('d')
RMSerrorX3=array('d')
MeanY3=array('d')
MeanerrorY3=array('d')
MeanX3=array('d')
MeanerrorX3=array('d')

bunch=1783


RMSY1_sim=array('d')
RMSerrorY1_sim=array('d')
RMSX1_sim=array('d')
RMSerrorX1_sim=array('d')
MeanY1_sim=array('d')
MeanerrorY1_sim=array('d')
MeanX1_sim=array('d')
MeanerrorX1_sim=array('d')

for i in range(1,20):
    hY1_1=f.Get("scanY1Move_b"+str(bunch)+"_%d"%(i))
    #hY1_sim=f_sim.Get("Beam2MoveY%d"%(25-i))
    hX1_1=f.Get("scanX1Move_b"+str(bunch)+"_%d"%(i))
    #hX1_sim=f_sim.Get("Beam2MoveX%d"%(i-1))

    hY1_2=f.Get("scanY2Move_b41_%d"%(i))
    hX1_2=f.Get("scanX2Move_b41_%d"%(i))

    #hY1_3=f.Get("scanY5Move_b41_%d"%(i))
    #hX1_3=f.Get("scanX5Move_b41_%d"%(i))

    vscan.append(i)
    vscanerror.append(0)
    vscan_sim.append(i)
    vscanerror_sim.append(0)

    funcGausY=ROOT.TF1("funcGausY","gaus",-10,10)
    funcGausX=ROOT.TF1("funcGausX","gaus",-10,10)
    hY1_1.ProjectionX().Fit("funcGausY")
    hX1_1.ProjectionY().Fit("funcGausX")
    RMSY1.append(funcGausY.GetParameter("Sigma")*0.00508)
    RMSerrorY1.append(funcGausY.GetParError(2)*0.00508)
    RMSX1.append(funcGausX.GetParameter("Sigma")*0.00508)
    RMSerrorX1.append(funcGausX.GetParError(2)*0.00508)
    MeanY1.append(funcGausY.GetParameter("Mean")*0.00508)
    MeanerrorY1.append(funcGausY.GetParError(1)*0.00508)
    MeanX1.append(funcGausX.GetParameter("Mean")*0.00508)
    MeanerrorX1.append(funcGausX.GetParError(1)*0.00508)

    hY1_2.ProjectionX().Fit("funcGausY")
    hX1_2.ProjectionY().Fit("funcGausX")
    RMSY2.append(funcGausY.GetParameter("Sigma")*0.00508)
    RMSerrorY2.append(funcGausY.GetParError(2)*0.00508)
    RMSX2.append(funcGausX.GetParameter("Sigma")*0.00508)
    RMSerrorX2.append(funcGausX.GetParError(2)*0.00508)
    MeanY2.append(funcGausY.GetParameter("Mean")*0.00508)
    MeanerrorY2.append(funcGausY.GetParError(1)*0.00508)
    MeanX2.append(funcGausX.GetParameter("Mean")*0.00508)
    MeanerrorX2.append(funcGausX.GetParError(1)*0.00508)

'''
    hY1_3.ProjectionX().Fit("funcGausY")
    hX1_3.ProjectionY().Fit("funcGausX")
    RMSY3.append(funcGausY.GetParameter("Sigma")*0.00508)
    RMSerrorY3.append(funcGausY.GetParError(2)*0.00508)
    RMSX3.append(funcGausX.GetParameter("Sigma")*0.00508)
    RMSerrorX3.append(funcGausX.GetParError(2)*0.00508)
    MeanY3.append(funcGausY.GetParameter("Mean")*0.00508)
    MeanerrorY3.append(funcGausY.GetParError(1)*0.00508)
    MeanX3.append(funcGausX.GetParameter("Mean")*0.00508)
    MeanerrorX3.append(funcGausX.GetParError(1)*0.00508)
'''
'''
    hY1_sim.ProjectionX().Fit("funcGausY")
    hX1_sim.ProjectionY().Fit("funcGausX")
    RMSY1_sim.append(funcGausY.GetParameter("Sigma")*0.00508)
    RMSerrorY1_sim.append(funcGausY.GetParError(2)*0.00508)
    RMSX1_sim.append(funcGausX.GetParameter("Sigma")*0.00508)
    RMSerrorX1_sim.append(funcGausX.GetParError(2)*0.00508)
    MeanY1_sim.append(funcGausY.GetParameter("Mean")*0.00508)
    MeanerrorY1_sim.append(funcGausY.GetParError(1)*0.00508)
    MeanX1_sim.append(funcGausX.GetParameter("Mean")*0.00508)
    MeanerrorX1_sim.append(funcGausX.GetParError(1)*0.00508)
'''
#graphY1RMS_sim=ROOT.TGraphErrors(len(vscan_sim),vscan_sim,RMSY1_sim,vscanerror_sim,RMSerrorY1_sim)
#graphY1Mean_sim=ROOT.TGraphErrors(len(vscan_sim),vscan_sim,MeanY1_sim,vscanerror_sim,MeanerrorY1_sim)
#graphX1RMS_sim=ROOT.TGraphErrors(len(vscan_sim),vscan_sim,RMSX1_sim,vscanerror_sim,RMSerrorX1_sim)
#graphX1Mean_sim=ROOT.TGraphErrors(len(vscan_sim),vscan_sim,MeanX1_sim,vscanerror_sim,MeanerrorX1_sim)

graphY1RMS=ROOT.TGraphErrors(len(vscan),vscan,RMSY1,vscanerror,RMSerrorY1)
graphY1Mean=ROOT.TGraphErrors(len(vscan),vscan,MeanY1,vscanerror,MeanerrorY1)
graphX1RMS=ROOT.TGraphErrors(len(vscan),vscan,RMSX1,vscanerror,RMSerrorX1)
graphX1Mean=ROOT.TGraphErrors(len(vscan),vscan,MeanX1,vscanerror,MeanerrorX1)

graphY2RMS=ROOT.TGraphErrors(len(vscan),vscan,RMSY2,vscanerror,RMSerrorY2)
graphY2Mean=ROOT.TGraphErrors(len(vscan),vscan,MeanY2,vscanerror,MeanerrorY2)
graphX2RMS=ROOT.TGraphErrors(len(vscan),vscan,RMSX2,vscanerror,RMSerrorX2)
graphX2Mean=ROOT.TGraphErrors(len(vscan),vscan,MeanX2,vscanerror,MeanerrorX2)

#graphY3RMS=ROOT.TGraphErrors(len(vscan),vscan,RMSY3,vscanerror,RMSerrorY3)
#graphY3Mean=ROOT.TGraphErrors(len(vscan),vscan,MeanY3,vscanerror,MeanerrorY3)
#graphX3RMS=ROOT.TGraphErrors(len(vscan),vscan,RMSX3,vscanerror,RMSerrorX3)
#graphX3Mean=ROOT.TGraphErrors(len(vscan),vscan,MeanX3,vscanerror,MeanerrorX3)

#graphY1RMS_sim.SetName("graphY1RMS_sim")
graphY1RMS.SetName("graphY1RMS")
#graphX1RMS_sim.SetName("graphX1RMS_sim")
graphX1RMS.SetName("graphX1RMS")

#graphY1Mean_sim.SetName("graphY1Mean_sim")
graphY1Mean.SetName("graphY1Mean")
#graphX1Mean_sim.SetName("graphX1Mean_sim")
graphX1Mean.SetName("graphX1Mean")

graphY2Mean.SetName("graphY2Mean")
#graphY3Mean.SetName("graphY3Mean")
graphX2Mean.SetName("graphX2Mean")
#graphX3Mean.SetName("graphX3Mean")

graphY2RMS.SetName("graphY2RMS")
#graphY3RMS.SetName("graphY3RMS")
graphX2RMS.SetName("graphX2RMS")
#graphX3RMS.SetName("graphX3RMS")


graphY1RMS.SetTitle("BeamSpot during Y1-Scan")
graphY1RMS.GetYaxis().SetTitleOffset(1.3)
graphY1RMS.GetXaxis().SetTitle("scanpoint")
graphY1RMS.GetYaxis().SetTitle("luminous region x-width [cm]")
graphY1Mean.SetTitle("BeamSpot during Y1-Scan")
graphY1Mean.GetYaxis().SetTitleOffset(1.3)
graphY1Mean.GetXaxis().SetTitle("scanpoint")
graphY1Mean.GetYaxis().SetTitle("luminous region x-mean [cm]")

graphX1RMS.SetTitle("BeamSpot during X1-Scan")
graphX1RMS.GetYaxis().SetTitleOffset(1.3)
graphX1RMS.GetXaxis().SetTitle("scanpoint")
graphX1RMS.GetYaxis().SetTitle("luminous region y-width [cm]")
graphX1Mean.SetTitle("BeamSpot during X1-Scan")
graphX1Mean.GetYaxis().SetTitleOffset(1.3)
graphX1Mean.GetXaxis().SetTitle("scanpoint")
graphX1Mean.GetYaxis().SetTitle("luminous region y-mean [cm]")

c1=ROOT.TCanvas("c1","c1",1000,600)
l1=ROOT.TLegend(0.5,0.7,0.7,0.9)
graphY1RMS.Draw("APE*")
#graphY1RMS_sim.SetMarkerColor(ROOT.kRed)
#graphY1RMS_sim.SetMarkerSize(2)
#graphY1RMS_sim.Draw("SAME*p")
graphY2RMS.SetMarkerStyle(23)
graphY2RMS.SetMarkerSize(1)
graphY2RMS.Draw("SAMEp")
#graphY3RMS.SetMarkerStyle(24)
#graphY3RMS.SetMarkerSize(1)
#graphY3RMS.Draw("SAMEp")


l1.AddEntry("graphY1RMS","Scan1","lep")
l1.AddEntry("graphY2RMS","Scan2","lep")
#l1.AddEntry("graphY3RMS","Scan5","lep")
#l1.AddEntry("graphY1RMS_sim","Simulation","lep")
l1.Draw()
c1.SaveAs("RMSX_YScan"+str(bunch)+".root")
c2=ROOT.TCanvas("c2","c2",1000,600)
l2=ROOT.TLegend(0.5,0.7,0.7,0.9)
graphY1Mean.Draw("APE*")
#graphY1Mean_sim.SetMarkerColor(ROOT.kRed)
#graphY1Mean_sim.SetMarkerSize(2)
#graphY1Mean_sim.Draw("SAME*")
graphY2Mean.SetMarkerStyle(23)
graphY2Mean.SetMarkerSize(1)
graphY2Mean.Draw("SAMEp")
#graphY3Mean.SetMarkerStyle(24)
#graphY3Mean.SetMarkerSize(1)
#graphY3Mean.Draw("SAMEp")


l2.AddEntry("graphY1Mean","Scan1","lep")
l1.AddEntry("graphY2Mean","Scan2","lep")
#l1.AddEntry("graphY3Mean","Scan5","lep")
#l2.AddEntry("graphY1Mean_sim","Simulation","lep")
l2.Draw()
c2.SaveAs("MeanX_YScan"+str(bunch)+".root")
c3=ROOT.TCanvas("c3","c3",1000,600)
l3=ROOT.TLegend(0.5,0.7,0.7,0.9)
graphX1RMS.Draw("APE*")
#graphX1RMS_sim.SetMarkerColor(ROOT.kRed)
#graphX1RMS_sim.SetMarkerSize(2)
#graphX1RMS_sim.Draw("SAME*")
graphX2RMS.SetMarkerStyle(23)
graphX2RMS.SetMarkerSize(1)
graphX2RMS.Draw("SAMEp")
#graphX3RMS.SetMarkerStyle(24)
#graphX3RMS.SetMarkerSize(1)
#graphX3RMS.Draw("SAMEp")


l3.AddEntry("graphX1RMS","Scan1","p")
l1.AddEntry("graphX2RMS","Scan2","lep")
#l1.AddEntry("graphX3RMS","Scan5","lep")
#l3.AddEntry("graphX1RMS_sim","Simulation","p")
l3.Draw()
c3.SaveAs("RMSY_XScan"+str(bunch)+".root")
c4=ROOT.TCanvas("c4","c4",1000,600)
l4=ROOT.TLegend(0.5,0.7,0.7,0.9)
graphX1Mean.Draw("APE*")
#graphX1Mean_sim.SetMarkerColor(ROOT.kRed)
#graphX1Mean_sim.SetMarkerSize(2)
#graphX1Mean_sim.Draw("SAME*")
graphX2Mean.SetMarkerStyle(23)
graphX2Mean.SetMarkerSize(1)
graphX2Mean.Draw("SAMEp")
#graphX3Mean.SetMarkerStyle(24)
#graphX3Mean.SetMarkerSize(1)
#graphX3Mean.Draw("SAMEp")


l4.AddEntry("graphX1Mean","Scan1","lep")
l1.AddEntry("graphX2Mean","Scan2","lep")
#l1.AddEntry("graphX3Mean","Scan5","lep")
#l4.AddEntry("graphX1Mean_sim","Simulation","p")
l4.Draw("same")
c4.SaveAs("MeanY_XScan"+str(bunch)+".root")
